"""
Candidate formulation runner and evaluator.

Usage:
    python formulate.py --candidate outputs/best_formulation.py
    python formulate.py --template
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import math
import time
import traceback
from pathlib import Path
from types import ModuleType
from typing import Any, Dict, List, Optional, Tuple

try:
    from ortools.linear_solver import pywraplp
except ImportError:
    pywraplp = None

from prepare import (
    EvaluationMetrics,
    ModelValidator,
    OUTPUTS_DIR,
    PROBLEM_EXTRACTED_FILE,
    TOY_EXAMPLES_FILE,
    generate_latex_skeleton,
    load_examples,
    load_problem,
    save_examples,
)


BEST_CANDIDATE_FILE = OUTPUTS_DIR / "best_formulation.py"
REQUIRED_FUNCTIONS = ("parse_instance", "build_model", "extract_solution", "format_output")
STATUS_NAMES = {
    0: "OPTIMAL",
    1: "FEASIBLE",
    2: "INFEASIBLE",
    3: "UNBOUNDED",
    4: "ABNORMAL",
    5: "MODEL_INVALID",
    6: "NOT_SOLVED",
}
CANDIDATE_TEMPLATE = '''"""
Candidate MILP formulation module generated by autoformalizer.
"""

from typing import Any, Dict, Tuple

from ortools.linear_solver import pywraplp


FORMULATION_NAME = "replace_me"


def parse_instance(input_text: str) -> Dict[str, Any]:
    raise NotImplementedError("Parse the problem-specific input format here.")


def build_model(instance: Dict[str, Any]) -> Tuple[pywraplp.Solver, Dict[str, Any]]:
    solver = pywraplp.Solver.CreateSolver("SCIP")
    if solver is None:
        raise RuntimeError("Could not create SCIP solver")
    context: Dict[str, Any] = {}
    return solver, context


def extract_solution(
    solver: pywraplp.Solver,
    instance: Dict[str, Any],
    context: Dict[str, Any],
) -> Dict[str, Any]:
    return {}


def format_output(solution: Dict[str, Any]) -> str:
    return ""


def describe_formulation(problem: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "summary": "Describe variables, constraints, and objective here.",
        "latex": "",
        "assumptions": [],
    }
'''


def write_candidate_template(output_file: Path) -> Path:
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(CANDIDATE_TEMPLATE, encoding="utf-8")
    return output_file


def _load_candidate_module(candidate_file: Path) -> Tuple[ModuleType, str]:
    code = candidate_file.read_text(encoding="utf-8")
    valid, error_message = ModelValidator.check_syntax(code)
    if not valid:
        raise SyntaxError(error_message)

    module_name = f"candidate_{candidate_file.stem}_{time.time_ns()}"
    spec = importlib.util.spec_from_file_location(module_name, candidate_file)
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not create import spec for {candidate_file}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module, code


def _status_name(status_code: int) -> str:
    return STATUS_NAMES.get(int(status_code), f"STATUS_{status_code}")


def _normalize_example(example: Dict[str, Any], index: int) -> Dict[str, Any]:
    return {
        "name": example.get("name") or f"example_{index}",
        "source": example.get("source", "unknown"),
        "input_text": example.get("input_text", ""),
        "expected_output_text": example.get("expected_output_text", ""),
        "expected_objective": example.get("expected_objective"),
        "explanation": example.get("explanation", ""),
    }


def _ensure_candidate_functions(module: ModuleType) -> None:
    if hasattr(module, "solve_instance"):
        return
    missing = [name for name in REQUIRED_FUNCTIONS if not hasattr(module, name)]
    if missing:
        raise AttributeError(
            "Candidate is missing required functions: " + ", ".join(sorted(missing))
        )


def _run_candidate(module: ModuleType, example: Dict[str, Any]) -> Dict[str, Any]:
    if pywraplp is None:
        raise ImportError("ortools is not installed. Run the project sync step first.")

    if hasattr(module, "solve_instance"):
        result = module.solve_instance(example["input_text"])
        if not isinstance(result, dict):
            raise TypeError("solve_instance() must return a dict")
        if "formatted_output" not in result:
            if hasattr(module, "format_output"):
                result["formatted_output"] = module.format_output(result)
            else:
                result["formatted_output"] = json.dumps(result, sort_keys=True)
        return result

    instance = module.parse_instance(example["input_text"])
    if not isinstance(instance, dict):
        raise TypeError("parse_instance() must return a dict")

    solver_bundle = module.build_model(instance)
    if isinstance(solver_bundle, tuple):
        if len(solver_bundle) != 2:
            raise TypeError("build_model() must return (solver, context)")
        solver, context = solver_bundle
    else:
        solver = solver_bundle
        context = {}

    if solver is None or not hasattr(solver, "Solve"):
        raise TypeError("build_model() did not return an OR-Tools solver")

    status_code = int(solver.Solve())
    solution = module.extract_solution(solver, instance, context)
    if not isinstance(solution, dict):
        raise TypeError("extract_solution() must return a dict")

    formatted_output = module.format_output(solution)
    result = dict(solution)
    result["formatted_output"] = formatted_output
    result["solver_status"] = status_code
    result["solver_status_name"] = _status_name(status_code)
    result["num_variables"] = int(solver.NumVariables())
    result["num_constraints"] = int(solver.NumConstraints())
    if "objective_value" not in result and status_code in (0, 1):
        result["objective_value"] = float(solver.Objective().Value())
    return result


def _compare_with_expected(example: Dict[str, Any], result: Dict[str, Any]) -> Dict[str, Any]:
    actual_output = ModelValidator.normalize_output(result.get("formatted_output", ""))
    expected_output = ModelValidator.normalize_output(example.get("expected_output_text", ""))
    expected_objective = example.get("expected_objective")

    output_match: Optional[bool] = None
    objective_match: Optional[bool] = None
    if expected_output:
        output_match = actual_output == expected_output
    if expected_objective is not None and result.get("objective_value") is not None:
        objective_match = math.isclose(
            float(expected_objective),
            float(result["objective_value"]),
            rel_tol=1e-6,
            abs_tol=1e-6,
        )

    solved = result.get("solver_status_name") in {"OPTIMAL", "FEASIBLE"}
    passed = solved
    if output_match is False:
        passed = False
    if objective_match is False:
        passed = False

    return {
        "passed": passed,
        "solved": solved,
        "actual_output": actual_output,
        "expected_output": expected_output,
        "output_match": output_match,
        "objective_match": objective_match,
    }


def _render_markdown_summary(
    problem: Dict[str, Any],
    candidate_file: Path,
    evaluation: Dict[str, Any],
    description: Dict[str, Any],
) -> str:
    lines = [
        f"# MILP Formulation: {evaluation.get('formulation_name', candidate_file.stem)}",
        "",
        f"Problem: {problem.get('title', 'Unknown problem')}",
        "",
        "## Scores",
        "",
        f"- Validity: {evaluation['validity_score']:.4f}",
        f"- Correctness: {evaluation['correctness_score']:.4f}",
        f"- Strength: {evaluation['constraint_strength']:.4f}",
        f"- Clarity: {evaluation['code_clarity']:.4f}",
        f"- Overall: {evaluation['overall_quality']:.4f}",
        "",
        "## Runtime",
        "",
        f"- Candidate: {candidate_file}",
        f"- Formulation time: {evaluation['formulation_time']:.3f}s",
        f"- Example pass rate: {evaluation['example_pass_rate']:.4f}",
        f"- Output match rate: {evaluation['output_match_rate']:.4f}",
        "",
        "## Summary",
        "",
        description.get("summary", "No description provided."),
        "",
    ]

    assumptions = description.get("assumptions") or []
    if assumptions:
        lines.append("## Assumptions")
        lines.append("")
        for assumption in assumptions:
            lines.append(f"- {assumption}")
        lines.append("")

    lines.append("## Example Results")
    lines.append("")
    for example_result in evaluation["example_results"]:
        lines.append(
            f"- {example_result['name']}: passed={example_result['passed']} "
            f"status={example_result.get('solver_status_name', 'ERROR')}"
        )
    lines.append("")
    return "\n".join(lines)


def evaluate_candidate(
    candidate_file: Path,
    problem: Optional[Dict[str, Any]] = None,
    examples: Optional[List[Dict[str, Any]]] = None,
    output_dir: Path = OUTPUTS_DIR,
    persist: bool = True,
) -> Dict[str, Any]:
    candidate_file = Path(candidate_file)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    if problem is None:
        problem = load_problem(PROBLEM_EXTRACTED_FILE)
    if examples is None:
        examples = load_examples(problem=problem)

    normalized_examples = [_normalize_example(example, idx) for idx, example in enumerate(examples, start=1)]
    if not normalized_examples:
        raise ValueError("No examples available for evaluation")

    start_time = time.time()
    evaluation: Dict[str, Any] = {
        "candidate_path": str(candidate_file),
        "problem_title": problem.get("title", "Unknown"),
        "example_results": [],
        "formulation_name": candidate_file.stem,
    }

    description: Dict[str, Any] = {
        "summary": "Candidate description unavailable.",
        "latex": generate_latex_skeleton(problem.get("title", "Problem"), problem.get("description", "")),
        "assumptions": [],
    }

    try:
        module, code = _load_candidate_module(candidate_file)
        _ensure_candidate_functions(module)
        if hasattr(module, "describe_formulation"):
            described = module.describe_formulation(problem)
            if isinstance(described, dict):
                description.update(described)
            elif isinstance(described, str):
                description["summary"] = described
        evaluation["formulation_name"] = getattr(module, "FORMULATION_NAME", candidate_file.stem)
    except Exception as exc:
        formulation_time = time.time() - start_time
        clarity = EvaluationMetrics.compute_code_clarity(
            candidate_file.read_text(encoding="utf-8") if candidate_file.exists() else ""
        )
        scores = EvaluationMetrics.combine_scores(0.0, 0.0, 0.0, clarity, formulation_time)
        evaluation.update(scores)
        evaluation["error"] = str(exc)
        evaluation["traceback"] = traceback.format_exc()
        if persist:
            (output_dir / "metrics.json").write_text(json.dumps(evaluation, indent=2), encoding="utf-8")
            (output_dir / "evaluation.json").write_text(json.dumps(evaluation, indent=2), encoding="utf-8")
        return evaluation

    num_examples = len(normalized_examples)
    passed_examples = 0
    solved_examples = 0
    matched_outputs = 0
    expected_output_examples = 0
    total_vars = 0
    total_constraints = 0

    for example in normalized_examples:
        result_record = {
            "name": example["name"],
            "source": example["source"],
        }
        try:
            result = _run_candidate(module, example)
            comparison = _compare_with_expected(example, result)
            result_record.update(result)
            result_record.update(comparison)

            if comparison["solved"]:
                solved_examples += 1
            if comparison["passed"]:
                passed_examples += 1
            if comparison["output_match"] is not None:
                expected_output_examples += 1
                if comparison["output_match"]:
                    matched_outputs += 1

            total_vars += int(result.get("num_variables", 0))
            total_constraints += int(result.get("num_constraints", 0))
        except Exception as exc:
            result_record["passed"] = False
            result_record["solved"] = False
            result_record["error"] = str(exc)
            result_record["traceback"] = traceback.format_exc()
        evaluation["example_results"].append(result_record)

    formulation_time = time.time() - start_time
    solve_rate = solved_examples / max(1, num_examples)
    pass_rate = passed_examples / max(1, num_examples)
    output_match_rate = (
        matched_outputs / expected_output_examples if expected_output_examples else 0.0
    )
    average_vars = total_vars / max(1, solved_examples)
    average_constraints = total_constraints / max(1, solved_examples)

    validity = 1.0 if solved_examples == num_examples else min(1.0, 0.35 + 0.65 * solve_rate)
    correctness = output_match_rate if expected_output_examples else min(0.85, pass_rate)
    if expected_output_examples:
        correctness = 0.8 * output_match_rate + 0.2 * pass_rate
    strength = ModelValidator.estimate_constraint_strength(
        int(round(average_vars)),
        int(round(average_constraints)),
    )
    clarity = EvaluationMetrics.compute_code_clarity(code)
    scores = EvaluationMetrics.combine_scores(
        validity,
        correctness,
        strength,
        clarity,
        formulation_time,
    )

    evaluation.update(scores)
    evaluation["example_pass_rate"] = float(pass_rate)
    evaluation["output_match_rate"] = float(output_match_rate)
    evaluation["num_variables"] = float(average_vars)
    evaluation["num_constraints"] = float(average_constraints)
    evaluation["description"] = description

    if persist:
        (output_dir / "metrics.json").write_text(json.dumps(evaluation, indent=2), encoding="utf-8")
        (output_dir / "evaluation.json").write_text(json.dumps(evaluation, indent=2), encoding="utf-8")
        (output_dir / "formulation.md").write_text(
            _render_markdown_summary(problem, candidate_file, evaluation, description),
            encoding="utf-8",
        )
        (output_dir / "formulation.tex").write_text(
            description.get("latex") or generate_latex_skeleton(problem.get("title", "Problem"), ""),
            encoding="utf-8",
        )

    return evaluation


def main() -> None:
    parser = argparse.ArgumentParser(description="Evaluate a candidate MILP formulation module")
    parser.add_argument(
        "--candidate",
        type=Path,
        default=BEST_CANDIDATE_FILE,
        help="Path to the candidate formulation module",
    )
    parser.add_argument(
        "--problem",
        type=Path,
        default=PROBLEM_EXTRACTED_FILE,
        help="Path to the extracted problem JSON",
    )
    parser.add_argument(
        "--examples",
        type=Path,
        default=TOY_EXAMPLES_FILE,
        help="Path to the toy example JSON file",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=OUTPUTS_DIR,
        help="Directory for metrics and rendered outputs",
    )
    parser.add_argument(
        "--template",
        action="store_true",
        help="Write a candidate template to the --candidate path and exit",
    )
    args = parser.parse_args()

    if args.template:
        template_path = write_candidate_template(args.candidate)
        print(f"Candidate template written to {template_path}")
        return

    if not args.candidate.exists():
        raise FileNotFoundError(
            f"Candidate file not found at {args.candidate}. "
            f"Run `python formulate.py --template --candidate {args.candidate}` first."
        )

    problem = load_problem(args.problem)
    examples = load_examples(args.examples, problem=problem)
    if not args.examples.exists():
        save_examples(examples, args.examples)

    evaluation = evaluate_candidate(
        args.candidate,
        problem=problem,
        examples=examples,
        output_dir=args.output_dir,
        persist=True,
    )

    print("=" * 70)
    print("FORMULATION EVALUATION")
    print("=" * 70)
    print(f"Problem:            {evaluation['problem_title']}")
    print(f"Candidate:          {args.candidate}")
    print(f"Formulation:        {evaluation['formulation_name']}")
    print(f"Validity:           {evaluation['validity_score']:.4f}")
    print(f"Correctness:        {evaluation['correctness_score']:.4f}")
    print(f"Constraint strength:{evaluation['constraint_strength']:.4f}")
    print(f"Code clarity:       {evaluation['code_clarity']:.4f}")
    print(f"Overall quality:    {evaluation['overall_quality']:.4f}")
    print(f"Example pass rate:  {evaluation['example_pass_rate']:.4f}")
    print(f"Output match rate:  {evaluation['output_match_rate']:.4f}")
    if evaluation.get("error"):
        print(f"Error:              {evaluation['error']}")
    print("=" * 70)


if __name__ == "__main__":
    main()
